# The URL the site will be built for
base_url = "https://tinker.ninja"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "hyde"
title = "tinker . ninja"
description = "random thoughts about hw & sw"

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
[markdown]
highlight_code = true

[extra]
hyde_links = [
    {url = "https://github.com/akonneker", name = "github"},
]
