[build]
publish = "public"
command = "npm run build"

[build.environment]
ZOLA_VERSION = "0.20.0"
NODE_VERSION = "22"

[context.deploy-preview]
command = 'npm run build:curves && zola build --base-url "$DEPLOY_PRIME_URL"'
