import { curveEquations } from './equations';
import { additionalCurves, fractalCurves } from './catalog';
import { fractalPoints } from './fractals';
export type Point = { x: number; y: number; t: number; segment: number };
import type { RollingSpec } from './curve-controls';
export type Curve = {
  rolling?: RollingSpec;
  sampleCount?: number;
  id: string;
  name: string;
  family: string;
  equation: string;
  equationTex?: string;
  description: string;
  history: string;
  uses: string;
  source: string;
  page: string;
  ranges: [number, number][];
  fn: (t: number, a: number) => [number, number];
  note?: string;
  fractal?: string;
  aliases?: string;
  settings?: Record<string, number>;
};
const pi = Math.PI;
const yates = 'https://archive.org/details/YatesHandbookCurves1947';
const initialCurves: Curve[] = [
  {
    id: 'lemniscate',
    name: 'Lemniscate of Bernoulli',
    family: 'Algebraic',
    equation: '(x² + y²)² = a²(x² − y²)',
    description:
      'A figure eight with two perfectly balanced lobes, meeting at the origin.',
    history:
      'Jacob Bernoulli studied this curve in 1694. Its name comes from the Latin for a ribbon, reflecting its flowing, double-looped shape.',
    uses: 'A useful example in the study of elliptic integrals, polar coordinates, and the geometry of symmetric paths.',
    source: yates,
    page: '143–147',
    ranges: [[0, 2 * pi]],
    fn: (t, a) => [
      (a * Math.cos(t)) / (1 + Math.sin(t) ** 2),
      (a * Math.sin(t) * Math.cos(t)) / (1 + Math.sin(t) ** 2),
    ],
  },
  {
    id: 'astroid',
    name: 'Astroid',
    family: 'Rolling curves',
    equation: 'x = a cos³t; y = a sin³t',
    description:
      'A four-cusped curve traced by a small circle rolling inside one four times its size.',
    history:
      'The astroid belongs to the cycloidal curves studied in connection with gear teeth. Yates discusses its double generation and geometric constructions.',
    uses: 'Gear geometry, envelopes of moving lines, and examples of cusps and finite arc length.',
    source: yates,
    page: '1–3',
    ranges: [[0, 2 * pi]],
    fn: (t, a) => [a * Math.cos(t) ** 3, a * Math.sin(t) ** 3],
  },
  {
    id: 'cardioid',
    name: 'Cardioid',
    family: 'Rolling curves',
    equation: 'r = a(1 − cos t)',
    description:
      'A heart-shaped curve with a single cusp and one axis of symmetry.',
    history:
      'A member of the epicycloid family, the cardioid is generated by one circle rolling around another of equal radius.',
    uses: 'Directional microphone response patterns and the study of optical caustics.',
    source: yates,
    page: '4–7',
    ranges: [[0, 2 * pi]],
    fn: (t, a) => [
      a * (1 - Math.cos(t)) * Math.cos(t),
      a * (1 - Math.cos(t)) * Math.sin(t),
    ],
  },
  {
    id: 'spiral',
    name: 'Archimedean spiral',
    family: 'Spirals',
    equation: 'r = at',
    description:
      'A spiral whose successive turns stay the same distance apart.',
    history:
      'Archimedes investigated the spiral produced by uniform rotation combined with uniform motion along a ray.',
    uses: 'Scroll mechanisms, spiral toolpaths, and converting rotation into uniform radial motion.',
    source: yates,
    page: '209–211',
    ranges: [[0, 6 * pi]],
    fn: (t, a) => [a * t * Math.cos(t), a * t * Math.sin(t)],
    note: 'Three turns shown; the complete spiral is unbounded.',
  },
  {
    id: 'cycloid',
    aliases: 'brachistochrone fastest descent',
    name: 'Cycloid',
    family: 'Rolling curves',
    equation: 'x = a(t − sin t); y = a(1 − cos t)',
    description:
      'The path of a point on the rim of a wheel rolling along a straight line.',
    history:
      'The cycloid became a central problem of seventeenth-century mathematics, connecting Galileo, Huygens, and the Bernoullis.',
    uses: 'The brachistochrone and tautochrone problems; cycloidal pendulums and motion design.',
    source: yates,
    page: '65–70',
    ranges: [[0, 4 * pi]],
    fn: (t, a) => [a * (t - Math.sin(t)), a * (1 - Math.cos(t))],
    note: 'Two arches of the repeating curve are shown.',
  },
  {
    id: 'catenary',
    name: 'Catenary',
    family: 'Transcendental',
    equation: 'x = at; y = a cosh t',
    description:
      'The shape of a uniform flexible chain hanging under its own weight.',
    history:
      'Leibniz, Huygens, and Johann Bernoulli found the equation of the hanging chain in 1691.',
    uses: 'Hanging chains and cables under their own weight; inverted catenary arches under corresponding loading.',
    source: yates,
    page: '12–14',
    ranges: [[-2.3, 2.3]],
    fn: (t, a) => [a * t, a * Math.cosh(t)],
  },
];
export const curves: Curve[] = [
  ...initialCurves,
  ...additionalCurves,
  ...fractalCurves,
].map((curve) => ({ ...curve, equationTex: curveEquations[curve.id] }));
export function sampleCurve(
  curve: Curve,
  a = 1,
  count = 1200,
  depth = 3,
): Point[] {
  if (curve.fractal) return fractalPoints(curve.fractal, depth, a);
  return curve.ranges.flatMap(([lo, hi], segment) =>
    Array.from({ length: count + 1 }, (_, i) => {
      const t = lo + ((hi - lo) * i) / count;
      const [x, y] = curve.fn(t, a);
      return { x, y, t, segment };
    }),
  );
}
export function bounds(points: Point[]) {
  let x0 = Infinity,
    x1 = -Infinity,
    y0 = Infinity,
    y1 = -Infinity;
  for (const p of points) {
    x0 = Math.min(x0, p.x);
    x1 = Math.max(x1, p.x);
    y0 = Math.min(y0, p.y);
    y1 = Math.max(y1, p.y);
  }
  return {
    cx: (x0 + x1) / 2,
    cy: (y0 + y1) / 2,
    span: Math.max(x1 - x0, y1 - y0, 0.1) * 1.3,
  };
}
export function svgPath(points: Point[], size = 300) {
  const b = bounds(points);
  return points
    .map(
      (p, i) =>
        `${i === 0 || p.segment !== points[i - 1].segment ? 'M' : 'L'}${(size / 2 + ((p.x - b.cx) * size) / b.span).toFixed(3)},${(size / 2 - ((p.y - b.cy) * size) / b.span).toFixed(3)}`,
    )
    .join(' ');
}
